name: Generate Files

on:
  pull_request:
    branches:
      - main

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Install dependencies
      working-directory: tools
      run: bundle install

    - name: Generate files
      working-directory: tools/utils
      run: ruby build.rb

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Generate files"
        git push